### ISSUE TITLE
Suggestion to extend the component

### ISSUE THREAD

**Issue by sbnedkov** [ghzcool/react-file-manager-ui#2]
Hey,

I'm not sure if you are still maintaining this project, but I want to thank you for creating it. I'm trying to spin up a simple file sharing application and found I can use it.

I also wonder about your intention of extending it. I'm new to React but I'd like to develop something new for it to fit my own needs. Basically I miss two features of the file sharing application I'm trying to develop - 1. Download file 2. Show file properties.

I gave some thought to this and to what will best fit the existing interface. Given it has a somewhat high-level API, maybe it is most practical to add the two operations with new buttons in the "toolbar" somewhere? A second low-level alternative is the introduction of event handlers so you can have on-click, on-hover, etc. on the files and folders, I like this less because you are handling these already to create effects and actions. Finally maybe the component might be extended to have a right-click - configurable context menu? I'll be happy to hear your thoughts.

Of course I can try to create this extension privately and keep it, without bothering you, but I thought I'd give some code back.

Cheers.

**Comment by ghzcool** [comment]
Thank you for your feedback.

I stopped with this project long time ago. I had some more ideas how to improve it but didn't have time for it then.
If you want to take it over and continue development feel free to make a fork or I can add you to this project.

Wish you the best.

**Comment by sbnedkov** [comment]
Got it, thanks. I will probably make the changes, I'll try to produce a PR soon and take a bit more of your time then if that's OK with you? I found some documentations so I'll try to follow your thoughts from the time.

**Comment by sbnedkov** [comment]
Thanks for merging #3 , I forgot to update the readme, I'll do that next.
